services:
  application:
    container_name: application
    build: .
    ports:
      - 80:8080
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:${POSTGRES_PORT}
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
