- name: Apply Postgres dumps
  hosts: all
  become_user: crab-stand
  become: yes
  vars:
    dumps: "{{ services }}"
  tasks:
    - name: Make sure psycopg2 is installed
      pip:
        name: psycopg2
        state: present

    - name: Import each dump into the respective database
      community.postgresql.postgresql_query:
        db: "{{ item.database }}"
        host: "{{ item.host }}"
        login_password: "{{ item.password }}"
        login_user: "{{ item.user }}"
        port: "{{ item.port }}"
        query: "{{ item.dump }}"
      loop: "{{ services }}"
